### Make http request to login with authorization header
POST {{url}}/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin1234"
}

> {%
    client.global.set("jwt_token", response.body.token);
%}

### Make http request to get user info
GET {{url}}/info/user
Content-Type: application/json

{
  "token": "{{jwt_token}}"
}

### Make http request to login
POST {{url}}/auth/login
Content-Type: application/json

{
  "username": "user1",
  "password": "test1234"
}