POST {{url}}/auth/login/

{
    "username": "usermk",
    "password": "test1234"
}

> {%
    client.global.set("jwt_token", response.body.token);
%}

###

POST {{url}}/books
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "title": "The Lord of the Rings",
  "year": 1954,
  "author": "J.R.R. Tolkien",
  "genre": "FICTION",
  "loanedOut": false
}

###

POST {{url}}/books
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
    "title": "Pulp Fiction",
    "year": 1994,
    "author": "Quentin Tarantino",
    "genre": "ACTION",
    "loanedOut": false
}

###

GET {{url}}/books/1
accept: application/json
Authorization: Bearer {{jwt_token}}

###

GET {{url}}/books
accept: application/json
Authorization: Bearer {{jwt_token}}

###

PUT {{url}}/books/1
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "title": "The Hobbit",
  "year": 1937,
  "author": "J.R.R. Tolkien",
  "genre": "FANTASY",
  "loanedOut": true
}

###

DELETE {{url}}/books/1
accept: application/json
Authorization: Bearer {{jwt_token}}

###

POST {{url}}/users
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "name": "John Doe",
  "password": "password",
  "userRole": "ADMIN",
  "books": [
    {
      "title": "The Lord of the Rings",
      "year": 1954,
      "author": "J.R.R. Tolkien",
      "genre": "FICTION",
      "loanedOut": true
    },
    {
      "title": "The Hobbit",
      "year": 1937,
      "author": "J.R.R. Tolkien",
      "genre": "FANTASY",
      "loanedOut": true
    }
  ]
}

###

GET {{url}}/users/1
accept: application/json
Authorization: Bearer {{jwt_token}}

###

GET {{url}}/users
accept: application/json
Authorization: Bearer {{jwt_token}}

###

PUT {{url}}/users/1
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "name": "Jane Doe",
  "password": "password",
  "userRole": "USER"
}

###

DELETE {{url}}/users/1
accept: application/json
Authorization: Bearer {{jwt_token}}

