### A simple get request to the test endpoint. No need for login
GET {{url}}/auth/test/

### Create a new user - this one will only get a USER role by default
POST {{url}}/auth/register/

{
    "username": "usermk",
    "password": "test1234"
}

### Login to get token
POST {{url}}/auth/login/

{
    "username": "user1",
    "password": "test1234"
}

> {%
    client.global.set("jwt_token", response.body.token);
%}

### Test user role
GET {{url}}/protected/user_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Test admin role
GET {{url}}/protected/admin_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Add admin role to user
POST {{url}}/auth/user/addrole/
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
    "role": "ADMIN"
}
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Add book
POST {{url}}/books
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "title": "The Lord of the Rings",
  "year": 1954,
  "author": "J.R.R. Tolkien",
  "genre": "FICTION"
}

### View all books
GET {{url}}/books
Accept: application/json

### View book by id
GET {{url}}/books/1
Accept: application/json

### View book by genre
GET {{url}}/books/genre/FICTION
Accept: application/json

### View book by title
GET {{url}}/books/title/The Lord of the Rings
Accept: application/json

### View book by release year
GET {{url}}/books/year/1954
Accept: application/json

### View book by author
GET {{url}}/books/author/J.R.R. Tolkien
Accept: application/json

### Update book by id
PUT {{url}}/books/1
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "title": "The Hobbit",
  "year": 1937,
  "author": "J.R.R. Tolkien",
  "genre": "FANTASY",
  "loanedOut": true
}

### Delete book by id
DELETE {{url}}/books/1
Accept: application/json
Authorization: Bearer {{jwt_token}}